global:
  scrape_interval:     10s # Scrape interval to every 10 seconds. Default value is every 1 minute.

scrape_configs:
  - job_name: 'micrometer'

    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080'] # host where our application is deployed
