global:
  scrape_interval: 2s
  scrape_timeout: 1s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
scrape_configs:
- job_name: prometheusdocker build -t my-prometheus .
  scrape_interval: 2s
  scrape_timeout: 1s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - docker.for.mac.host.internal:8080
