- hosts: localhost

  tasks:

    - name: Create Keycloak directory
      file:
        path: /opt/keycloak
        state: directory
        mode: 0777

    - name: Extract Keycloak
      unarchive:
        src: keycloak-3.4.0.Final.tar
        dest: /opt/

    - name: create keycloak master admin user
      command: /opt/keycloak-3.4.0.Final/bin/add-user-keycloak.sh -r master -u admin -p admin

    - name: start keycloak in background
      shell: nohup /opt/keycloak-3.4.0.Final/bin/standalone.sh &

    - name: "Generate keycloak auth token"
      uri:
        url: "http://localhost:8080/auth/realms/master/protocol/openid-connect/token"
        method: POST
        body: "client_id=admin-cli&username=admin&password=admin&grant_type=password"
        validate_certs: no
      register: keycloak_auth_response
      until: keycloak_auth_response.status == 200
      retries: 600
      delay: 2

    - name: "Create dolphin realm"
      uri:
        url: "http://localhost:8080/auth/admin/realms"
        method: POST
        body: "{{ lookup('file','default-realm.json') }}"
        validate_certs: no
        body_format: json
        headers:
          Authorization: "bearer {{ keycloak_auth_response.json.access_token }}"
        status_code: 201

    - name: "Create default-bearer client in dolphin realm"
      uri:
        url: "http://localhost:8080/auth/admin/realms/dolphin-realm/clients"
        method: POST
        body: "{{ lookup('file','default-client.json') }}"
        validate_certs: no
        body_format: json
        headers:
          Authorization: "bearer {{ keycloak_auth_response.json.access_token }}"
        status_code: 201

    - name: "Create user in dolphin realm"
      uri:
        url: "http://localhost:8080/auth/admin/realms/dolphin-realm/users"
        method: POST
        body: "{{ lookup('file','default-user.json') }}"
        validate_certs: no
        body_format: json
        headers:
          Authorization: "bearer {{ keycloak_auth_response.json.access_token }}"
        status_code: 201

    - name: Shutdown server
      shell: /opt/keycloak-3.4.0.Final/bin/jboss-cli.sh --connect --command=:shutdown >> shutdown.log
      args:
        creates: shutdown.log
