version: '2'
services:

  app-server:
    image: metrics-sample-app-server
    build: ../server-spring
    ports:
      - "8080:8080"

  prometheus:
    image: metrics-sample-prometheus
    build: prometheus
    ports:
      - "9090:9090"

  grafana:
    image: metrics-sample-grafana
    build: grafana
    ports:
      - "3000:3000"
